config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root to: redirect("/messages")
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true

  def to_html
    MessagesController.render(self)
  end

  def to_form_html
    MessagesController.render(partial: "form", assigns: {message: self})
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include CableReady::Broadcaster
  before_action :set_messages
  before_action :set_message, only: %i[ edit update destroy ]

  def index
    @messages = Message.all
  end

  def new
    @message = @messages.new
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      render operations: cable_car
        .append("#messages", html: @message.to_html)
        .remove("#new_message")
        .push_state(url: messages_path)
    else
      render operations: cable_car.outer_html(@message, html: @message.to_form_html)
    end
  end

  def update
    if @message.update(message_params)
      render operations: cable_car
        .outer_html(@message, html: @message.to_html)
        .push_state(url: messages_path)
    else
      render operations: cable_car.outer_html(@message, html: @message.to_form_html)
    end
  end

  def destroy
    @message.destroy
    render operations: cable_car.remove(@message)
  end

  private
    def set_messages
      @messages = Message.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include CableReady::Broadcaster
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
    respond_to do |format|
      format.html { render }
      format.json { render operations: cable_car.inner_html(@posts, html: self.class.render(@posts)) }
    end
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    render operations: cable_car.append(selector: "#posts", html: render_form(@post))
  end

  # GET /posts/1/edit
  def edit
    render operations: cable_car.outer_html(selector: @post, html: render_form(@post))
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      render operations: cable_car
        .append(selector: "#posts", html: render_post(@post))
        .remove(selector: "#new_post")
    else
      render operations: cable_car.outer_html(selector: @post, html: render_form(@post))
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      render operations: cable_car.outer_html(selector: @post, html: render_post(@post))
    else
      render operations: cable_car.outer_html(selector: @post, html: render_form(@post))
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    render operations: cable_car.remove(selector: @post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content)
    end

    def render_post post
      self.class.render(post)
    end

    def render_form post
      self.class.render(partial: "form", locals: {post: post})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CableCarMessages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="cable-car">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="card mb-3" id="<%= dom_id(@message) %>">
  <div class="card-body">
    <%= form_with(model: @message, data: {remote: true, type: "json"}) do |form| %>
    <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% @message.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= form.label :content, class: "form-control-label" %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="actions mt-2 d-flex">
      <%= form.submit class: "btn btn-success" %>
      <%= link_to "Cancel", messages_path, class: "btn btn-outline-secondary ms-2" %>
    </div>
    <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<%- if message == @message %>
  <%= render "form" %>
<%- else %>
  <div class="card mb-3" id="<%= dom_id(message) %>">
    <div class="card-body">
      <%= message.content %>

      <%- unless @message %>
        <div class="mt-2">
          <%= link_to "[edit]", edit_message_path(message) %>
          <%= link_to "[delete]", message, data: {remote: true, type: "json", method: "DELETE", confirm: "Are you sure?"} %>
        </div>
      <%- end %>
    </div>
  </div>
<%- end %>

app/views/messages/_messages.html.erb
<div id="messages" class="mb-5">
  <%= render @messages %>
</div>

app/views/messages/index.html.erb
<h1>Messages</h1>

<div id="messages" class="mb-5">
  <%= render @messages %>
</div>

<%- unless @message %>
  <%= link_to "New Message", new_message_path %>
<%- end %>

app/views/messages/new.html.erb
<h1>Messages</h1>

<div id="messages" class="mb-5">
  <%= render @messages %>
</div>

<%= render "form" %>

app/views/posts/_form.html.erb
<%= form_with(model: post, data: {remote: true}, id: dom_id(post)) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <%= link_to "Cancel", posts_path, data: {remote: true, type: "json"} %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>">
  <dl>
          <dt>Content</dt>
      <dd><%= post.content %></dd>
      </dl>

  <div class="actions">
    <td><%= link_to '[show]', post %></td>
    <td><%= link_to '[edit]', edit_post_path(post), data: {remote: true}%></td>
    <td><%= link_to '[destroy]', post, method: :delete, data: { confirm: 'Are you sure?', remote: true } %></td>
  </div>
</div>

app/views/posts/index.html.erb
<div data-controller="cable-car">
  <h1>Posts</h1>

  <div id="posts">
    <%= render @posts %>
  </div>

  <br>

  <%= link_to 'New Post', new_post_path, data: {remote: true} %>
</div>

app/views/posts/show.html.erb
<div data-controller="cable-car">
  <%= render @post %>

  <%= link_to 'Back', posts_path %>
</div>